
#goal definition
geometry_msgs/PoseStamped[] poses
---
#result definition

# Error codes
uint32 NONE=0
uint32 GOAL_OCCUPIED=101 #目标点被占用
uint32 TIMEOUT=102 #规划超时
uint32 NO_VALID_PATH=103 #无可通行路线

uint32 error_code
---
#feedback definition
