#匹配类型
uint8 LOCAL_MATCH=1 #局部重定位位姿(需要提供pose_robot)
uint8 GLOBAL_MATCH=2 #全局重定位位姿(不需要提供pose_ref，定位算法进行自动匹配)

#goal definition
geometry_msgs/PoseStamped pose_ref #初始参考位姿
uint8 match_type #匹配类型（LOCAL_MATCH、GLOBAL_MATCH）
---
geometry_msgs/PoseStamped[] poses_robot #机器人位姿

bool success #结果
uint32 error_code #错误码
string message #失败原因

#错误码
uint32 NONE=0
uint32 UNKNOWN=200
uint32 TF_ERROR=201 #TF错误
uint32 SENSOR_ERROR=202 #传感器异常
uint32 LOW_CONFIDENCE=203 #低置信度